on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: Install depends
      run: |
        sudo apt install gcc libc6-dev
        sudo apt install libx11-dev xorg-dev libxtst-dev
        sudo apt install libpng++-dev
        sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
        sudo apt install xsel xclip
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
